myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from . import views
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve
urlpatterns = [
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root':
settings.MEDIA_ROOT}),
re_path(r'^static/(?P<path>.*)$', serve, {'document_root':
settings.STATIC_ROOT}),
    path('admin/', admin.site.urls),
    path('', views.home_page),
    path('about/', views.about_page),
    path('posts/', include('posts.urls')),    path('posts/', include('posts.urls')),
    path('users/', include('users.urls')),

]

# Suggested code may be subject to a license. Learn more: ~LicenseLog:2112332624.
# Suggested code may be subject to a license. Learn more: ~LicenseLog:83515229.
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myproject/posts/urls.py
from django.urls import path
from . import views

app_name = "posts"

urlpatterns = [
    path('', views.posts_list,name="list"),
    path('new-post/', views.post_new,name="new"),
    path('<slug:slug>', views.post_page,name="page"),

]

myproject/users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path('register/', views.register_view,name="register"),
    path('login/', views.login_view,name="login"),
    path('logout/', views.logout_view,name="logout"),

]

myproject/posts/models.py
from django.db import models
from django.contrib.auth.models import User


class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    slug = models.SlugField()
    banner = models.ImageField(default="fallback.png",blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE,default=None)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    # def __init__(self,title,content,slug=None):
    #     self.title = title
    #     self.content = content
    #     self.slug = slug
  
    
    def __str__(self):
        return self.title

myproject/users/models.py
from django.db import models

# Create your models here.

myproject/posts/forms.py
from django import forms
from . import models

class CreatePost(forms.ModelForm):
    
    class Meta:
        model = models.Post
        fields = ["title","content","slug","banner"]

myproject/myproject/views.py
from django.shortcuts import render

def home_page(request):
    return render(request,'home.html')


def about_page(request):
    return render(request,'about.html')

myproject/posts/views.py
from django.shortcuts import render, redirect
# Suggested code may be subject to a license. Learn more: ~LicenseLog:733839661.
from .models import Post
from django.contrib.auth.decorators import login_required
from . import forms
# Create your views here.
def posts_list(request):
    posts = Post.objects.all().order_by("created_at")
    return render(request,'posts/posts_list.html',{'posts':posts})

@login_required(login_url='/users/login')
def post_new(request):
    if request.method == 'POST':
        form = forms.CreatePost(request.POST,request.FILES)
        if form.is_valid():
            newpost = form.save(commit=False)
            newpost.author  = request.user
            newpost.save()
            return redirect('posts:list')
    else:
        form = forms.CreatePost()
    return render(request,'posts/post_new.html',{'form':form})


def post_page(request,slug):
    post = Post.objects.get(slug=slug)
    return render(request,'posts/post_page.html',{'post':post})

myproject/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

def register_view(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            login(request,form.save())
            return redirect('posts:list')
    else:
        form = UserCreationForm()
    return render(request,'users/register.html',{'form':form})

def login_view(request):
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            login(request,form.get_user())
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('posts:list')
    else:
        form = AuthenticationForm()
    return render(request,'users/login.html',{'form':form})

def logout_view(request):
    if request.method == "POST":
        logout(request)
        return redirect('posts:list')

myproject/posts/templates/posts/post_new.html
{% extends 'layout.html' %}
{% block title %}Post New{% endblock %}
{% block content %}
<section>
    <h1>New Post</h1>
    <form action="{% url 'posts:new' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{form}}
        <button type="submit">Submit</button>
    </form>
</section>
    {% endblock %}

myproject/posts/templates/posts/post_page.html
{% extends 'layout.html' %}
{% block title %}Post Page{% endblock %}
{% block content %}
<section>
    <img class"banner" src="{{post.banner.url}}" alt="{{post.title}}">
    <h1>{{post.title}}</h1>
    <p>{{post.created_at}}</p>
    <p>{{post.slug}}</p>
    <p>{{post.content}}</p>
    <p>by {{post.author}}</p>

    
</section>
    {% endblock %}

myproject/posts/templates/posts/posts_list.html
{% extends 'layout.html' %}
{% block title %}Posts List{% endblock %}
{% block content %}
<section>

    <h1>Posts</h1>
    {% for post in posts %}
     <article class="post">
        <h2>
            <a href="{% url 'posts:page' slug=post.slug %}">
                {{post.title}}
            </a>
        </h2>
        <p>{{post.content}}</p>
        <p>{{post.created_at}}</p>
     </article>
    {% endfor %}
</section>
    {% endblock %}

myproject/templates/about.html
{% extends 'layout.html' %}
{% block title %}About{% endblock %}
{% block content %}
    <h1>About</h1>
    <p>checkout the <a href="/">home</a> page</p>
    {% endblock %}

myproject/templates/home.html
{% extends 'layout.html' %}
{% block title %}Home{% endblock %}
{% block content %}
    <h1>Home</h1>
    <p>checkout the <a href="/about">about</a> page</p>
{% endblock %}

myproject/templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title%}
            Django App
        {% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script defer src="{% static 'js/main.js' %}"></script>
</head>
<body>
    <nav>
        <a href="/">
            <span role="img" aria-label="home">
                🏠
            </span>
        </a> |
        <a href="/about">
            <span role="img" aria-label="about">
                😀
            </span>
        </a> |
        <a href="{% url 'posts:list' %}">
            <span role="img" aria-label="post">
            🪖
            </span>
        </a> |
        {% if user.is_authenticated %}
        
        <a href="{% url 'posts:new' %}">
            <span role="img" aria-label="mew-post">
            ✍️
            </span>
        </a> |
        <form class="" method="POST" action="{% url 'users:logout' %}">
            {% csrf_token %}
            <button type="submit">
                <span role="img" aria-label="logout" title="logout">
                    🔓
                </span>

            </button>
        </form>
        {% else %}
        <a href="{% url 'users:register' %}">
            <span role="img" aria-label="register" title="register">
                🗽
            </span>
        </a> |
        <a href="{% url 'users:login' %}">
            <span role="img" aria-label="login" title="login">
                🔒
            </span>
        </a> 
            {% endif %}
    </nav>
    <main>
        {% block content %}
        {% endblock %}

    </main>
</body>
</html>

myproject/users/templates/users/login.html
{% extends 'layout.html' %}
{% block title %}Login{% endblock %}
{% block content %}
<section>
    <h1>User login</h1>
{% comment %} Suggested code may be subject to a license. Learn more: ~LicenseLog:3158449479. {% endcomment %}
    <form class="form-with-validation" action="{% url 'users:login' %}" method="post">
        {% csrf_token %}
        {{form}}
        {% if request.GET.next %}
        <input type="hidden" name="next" value="{{request.GET.next}}">
        {% endif %}
        <button class="form-submit" type="submit">Submit</button>
    </form>
</section>
    {% endblock %}

myproject/users/templates/users/register.html
{% extends 'layout.html' %}
{% block title %}Register{% endblock %}
{% block content %}
<section>
    <h1>Register a new user</h1>
{% comment %} Suggested code may be subject to a license. Learn more: ~LicenseLog:3158449479. {% endcomment %}
    <form class"form-with-validation" action="{% url 'users:register' %}" method="post">
        {% csrf_token %}
        {{form}}
        <button class="form-submit" type="submit">Submit</button>
    </form>
</section>
    {% endblock %}